version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  python-app:
    build: ./python-app
    depends_on:
      - mailhog
